export const ADD_FAVORITES="ADD_FAVORITES";
export const ADD_DETAILS = "ADD_DETAILS";
export const REMOVE_FAVORITES = "REMOVE_FAVORITES";
export const ADD_LOGGED_PROFILE = "ADD_LOGGED_PROFILE";
export const ADD_LOGGED_USER = "ADD_LOGGED_USER";
export const ADD_TOGGLE_LOGIN = "ADD_TOGGLE_LOGIN";
